obstacle_range: 5.0
raytrace_range: 5.0
footprint: [[0.18, 0.13], [0.18, -0.13], [-0.18, -0.13], [-0.18, 0.13]]
footprint_inflation: 0.05
#robot_radius: 0.3

#inflation_radius: 0.4
#cost_scaling_factor: 0.8
max_obstacle_height: 1
min_obstacle_height: 0.0
observation_sources: scan
scan: {sensor_frame: base_laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
