global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 5.0  #10
   publish_frequency: 5.0   #10
   static_map: true
  # rolling_window: false
  # width: 6.0
   #height: 6.0
   resolution: 0.4 #地图分辨率
   transform_tolerance: 1.0   #等待坐标变换发布的超时时间
   #map_type: costmap

   
