local_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 10.0  #10
   publish_frequency: 10.0   #10
   static_map: false
   rolling_window: true
   width: 3  
   height: 3
   resolution: 0.4 #地图分辨率
   transform_tolerance: 1.0 #等待坐标变换发布的超时时间


