TebLocalPlannerROS:

 odom_topic: /odometry/filtered

 # Trajectory

 teb_autosize: True
 dt_ref: 0.3  #参考轨迹的离散间隔
 dt_hysteresis: 0.s1
 max_samples: 500
 global_plan_overwrite_orientation: true  #true    teb_local_planner 规划局部路径时是否覆盖掉全局路径点的方位角。
 allow_init_with_backwards_motion: True
 max_global_plan_lookahead_dist: 1.2 #1.2    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 global_plan_viapoint_sep: 0.1 #设置为正值(考虑全局points) 含义是在global_planner轨迹上间隔多远会有一个viapoint插入。设置为1就是1m一个viapoint
 global_plan_prune_distance: 1 #via 距离修建
 exact_arc_length: False
 feasibility_check_no_poses: 2
 publish_feedback: False

 # Robot

 max_vel_x: 1.0 #1.65
 max_vel_x_backwards: 1.0 #1.65
 max_vel_y: 1.0
 max_vel_theta: 2.5 # 4  5 the angular velocity is also bounded by min_turning_radius in case of a carlike robot (r = v / omega)
 acc_lim_x: 2.5 #3.5  7   10
 acc_lim_y: 2.5
 acc_lim_theta: 5.0 #5  10  100

 # ********************** Carlike robot parameters ********************
 #min_turning_radius: 0       # Min turning radius of the carlike robot (compute value using a model or adjust with rqt_reconfigure manually)
 #wheelbase: 0                 # Wheelbase of our robot
 #cmd_angle_instead_rotvel: false # stage simulator takes the angle instead of the rotvel as input (twist message)
 # ********************************************************************

 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "point"
   radius: 0.2 # for type "circular"
   line_start: [-0.025, 0.0] # for type "line"
   line_end: [0.025, 0.0] # for type "line"
   front_offset: 0.2 # for type "two_circles"
   front_radius: 0.2 # for type "two_circles"
   rear_offset: 0.2 # for type "two_circles"
   rear_radius: 0.2 # for type "two_circles"
   vertices: [ [0.18, -0.13], [0.18, -0.13], [0.18, -0.13], [-0.18, -0.13], [-0.18, 0.13], [-0.18, 0.13], [0.18, 0.13], [0.18, 0.13], [0.18, 0.13] ] # for type "polygon"

 # GoalTolerance
    
 xy_goal_tolerance: 0.35
 yaw_goal_tolerance: 3.2
 free_goal_vel: false
 complete_global_plan: True
    
 # Obstacles
    
 min_obstacle_dist: 0.5 # 0.35 最小避障距离 This value must also include our robot's expansion, since footprint_model is set to "line".
 inflation_dist: 0.5   #0.4 障碍物周围的缓冲区，进缓冲区会导致规划器减速，这个值得比min_obstacle_dist大才有效
 include_costmap_obstacles: True #True   必须设置成true才能规避实时探测到的建图时不存在的障碍物
 costmap_obstacles_behind_robot_dist: 0.5     #1  考虑后方n米范围内的障碍物
 obstacle_poses_affected: 30 #30 因为障碍物而受到影响的poses数量（基于距离障碍物最近的pose，向两边扩展的点数）
 obstacle_association_force_inclusion_factor: 2.5 # the obstacles that will be taken into account are those closer than min_obstacle_dist*factor, if legacy is false
 obstacle_association_cutoff_factor: 10.0 # the obstacles that are further than min_obstacle_dist * factor will not be taken into account, if legacy is false

 dynamic_obstacle_inflation_dist: 0.6
 include_dynamic_obstacles: False # ture

 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
    
 no_inner_iterations: 4
 no_outer_iterations: 3
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1 #0.1 一次性修改全部惩罚项。注意，谨慎操作
 obstacle_cost_exponent: 4
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000 #1000 面向non-holonomic robots的运动学约束的权重。
 weight_kinematics_forward_drive: 100
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 80 # must be > 0
 weight_shortest_path: 0
 weight_obstacle: 100    # 避障在整个优化函数中的权重
 weight_inflation: 0.2
 weight_dynamic_obstacle: 10 # not in use yet
 weight_dynamic_obstacle_inflation: 0.2
 weight_viapoint: 100 #1  相关权重，提高和降低会明显改变输出轨迹的跟随力度
 weight_adapt_factor: 2

 # Homotopy Class Planner

 enable_homotopy_class_planning: false  #false   当True，teb会同时搜寻多条路径并选取一条更可行的。   设置为true测试失败
 enable_multithreading: True
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_prefer_initial_plan: 0.95
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False

 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 roadmap_graph_area_length_scale: 1.0
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_heading_threshold: 0.45
 switching_blocking_period: 0.0
 viapoints_all_candidates: True #如果设置为true的话，所有的输出轨迹，都会受到影响。否则只有属于global_planner的拓扑类所属轨迹会follow viapoints
 delete_detours_backwards: True
 max_ratio_detours_duration_best_duration: 3.0
 visualize_hc_graph: False
 visualize_with_time_as_z_axis_scale: False

# Recovery
 
 shrink_horizon_backup: True
 shrink_horizon_min_duration: 10
 oscillation_recovery: True
 oscillation_v_eps: 0.1
 oscillation_omega_eps: 0.1
 oscillation_recovery_min_duration: 10
 oscillation_filter_duration: 10
